[project]
name = "MIST-Explorer"
version = "0.1.0"
description = "Our application is a powerful and intuitive tool designed for researchers and scientists in the field of single-cell proteomics. It allows users to load, visualize, and analyze protein distribution at the single-cell level. By providing a user-friendly interface, the app enables seamless exploration of protein expression data, helping to uncover insights into cellular functions, interactions, and heterogeneity."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "astroalign>=2.6.1",
    "diplib>=3.5.2",
    "itk-elastix>=0.23.0",
    "matplotlib>=3.10.3",
    "numpy==1.26.4",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.0",
    "pillow>=11.2.1",
    "pyclesperanto-prototype>=0.24.5",
    "pyqt6>=6.9.1",
    "pystackreg>=0.2.8",
    "qtrangeslider>=0.1.5",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.0",
    "seaborn>=0.13.2",
    "sep>=1.4.1",
    "simpleitk>=2.5.2",
    "siphash24>=1.7",
    "stardist>=0.9.1",
    "tensorflow[and-cuda]==2.10.0",
    "tensorflow-io-gcs-filesystem==0.31.0",
    "umap>=0.1.1",
]
[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true # This forces the agent to use type hints

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
qt_api = "pyqt6"
python_files = "test_*.py"
