# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets



# class SelectFile(QtWidgets.QWidget):
#     def __init__(self, name, ):
#         super().__init__()

class OpenFilesDialog(QtWidgets.QDialog):

    def __init__(self):
        super().__init__()
        self.setupUi()
        # self.filename1 = None
        # self.filename2 = None
        # self.filename3 = None
        # self.filename4 = None


    def setupUi(self):
        self.setObjectName("Dialog")
        self.resize(270, 228)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label1 = QtWidgets.QLabel(self)
        self.label1.setMinimumSize(QtCore.QSize(100, 0))
        self.label1.setObjectName("label1")
        self.horizontalLayout_3.addWidget(self.label1)
        self.button1 = QtWidgets.QPushButton(self)
        self.button1.setObjectName("button1")
        self.horizontalLayout_3.addWidget(self.button1)
        self.filename1 = QtWidgets.QLabel(self)
        self.filename1.setMinimumSize(QtCore.QSize(100, 0))
        self.filename1.setObjectName("filename1")
        self.horizontalLayout_3.addWidget(self.filename1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label2 = QtWidgets.QLabel(self)
        self.label2.setMinimumSize(QtCore.QSize(100, 0))
        self.label2.setObjectName("label2")
        self.horizontalLayout_4.addWidget(self.label2)
        self.button2 = QtWidgets.QPushButton(self)
        self.button2.setObjectName("button2")
        self.horizontalLayout_4.addWidget(self.button2)
        self.filename2 = QtWidgets.QLabel(self)
        self.filename2.setMinimumSize(QtCore.QSize(100, 0))
        self.filename2.setObjectName("filename2")
        self.horizontalLayout_4.addWidget(self.filename2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label3 = QtWidgets.QLabel(self)
        self.label3.setMinimumSize(QtCore.QSize(100, 0))
        self.label3.setObjectName("label3")
        self.horizontalLayout_5.addWidget(self.label3)
        self.button3 = QtWidgets.QPushButton(self)
        self.button3.setObjectName("button3")
        self.horizontalLayout_5.addWidget(self.button3)
        self.filename3 = QtWidgets.QLabel(self)
        self.filename3.setMinimumSize(QtCore.QSize(100, 0))
        self.filename3.setObjectName("filename3")
        self.horizontalLayout_5.addWidget(self.filename3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label4 = QtWidgets.QLabel(self)
        self.label4.setMinimumSize(QtCore.QSize(100, 0))
        self.label4.setObjectName("label4")
        self.horizontalLayout_6.addWidget(self.label4)
        self.button4 = QtWidgets.QPushButton(self)
        self.button4.setObjectName("button4")
        self.horizontalLayout_6.addWidget(self.button4)
        self.filename4 = QtWidgets.QLabel(self)
        self.filename4.setMinimumSize(QtCore.QSize(100, 0))
        self.filename4.setObjectName("filename4")
        self.horizontalLayout_6.addWidget(self.filename4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi()
        self.buttonBox.accepted.connect(self.accept) # type: ignore
        self.buttonBox.rejected.connect(self.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "Select Files"))
        self.label1.setText(_translate("self", "Reference Image"))
        self.button1.setText(_translate("self", "Select File"))
        self.label2.setText(_translate("self", "Protein Image"))
        self.button2.setText(_translate("self", "Select File"))
        self.label3.setText(_translate("self", "Color Code"))
        self.button3.setText(_translate("self", "Select File"))
        self.label4.setText(_translate("self", "Decoding File"))
        self.button4.setText(_translate("self", "Select File"))


    def on_button1_pressed(self):
        filename1, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Open Image File", "", "Images (*.png *.xpm *.jpg *.bmp *.gif *.tif);;All Files (*)")
        self.filename1.setText(filename1)

    def on_button2_pressed(self):
        filename2, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Open Image File", "", "Images (*.png *.xpm *.jpg *.bmp *.gif *.tif);;All Files (*)")
        self.filename2.setText(filename2)

    def on_button3_pressed(self):
        filename3, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Open Image File", "", "Images (*.png *.xpm *.jpg *.bmp *.gif *.tif);;All Files (*)")
        self.filename3.setText(filename3)

    def on_button4_pressed(self):
        filename4, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Open Image File", "", "Images (*.png *.xpm *.jpg *.bmp *.gif *.tif);;All Files (*)")
        self.filename4.setText(filename4)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    self = OpenFilesDialog()
    self.show()
    sys.exit(app.exec())
